---
title: 📚 TDD Chapter 1~3
date: 2022-05-01
description: 사내 스터디 - 파이썬을 이용한 클린 코드를 위한 테스트 주도 개발 챕터 1 ~ 3
---

> [파이썬을 이용한 클린 코드를 위한 테스트 주도 개발](https://product.kyobobook.co.kr/detail/S000001556139)

# 용어
### 기능 테스트(Functional Test)
- 사용자 관점에서 애플리케이션 외부를 테스트 하는 것
- FT 자체가 애플리케이션 사양이 될 수 있음을 의미
- 제대로 된 기능성을 갖춘 애플리케이션을 구축하도록 도우며, 그 기능성이 망가지지 않도록 보장
- 상위 레벨의 개발을 주도
- ex) 사이트 접속 가능 여부

### 단위 테스트(Unit Test)
- 프로그래머 관점에서 그 내부를 테스트 하는 것
- 깔끔하고 버그 없는 코드를 작성하도록 돕는다.
- 하위 레벨의 개발을 주도
- ex) 코드

### 사용자 스토리(User Story)
- 사용자 관점에서 어떻게 애플리케이션이 동작해야 하는지 기술한 것
- 기능 테스트 구조화를 위해 사용

### 예측된 실패(Expected failure)
- 의도적으로 구현한 테스트 실패를 의미

<br>
<br>

# TDD 작업 순서
1. 기능 테스트를 작성해서 사용자 관점의 새로운 기능성을 정의하는 것부터 시작한다.
2. 기능 테스트가 실패하고 나면 어떻게 코드를 작성해야 테스트를 통과할지를 생각한다. 이 시점에 단위 테스트를 이용해서 어떻게 코드가 동작해야 하는 지 정의한다.
4. 단위 테스트가 실패하고 나면 단위 테스트를 통과할 수 있을 정도의 최고한의 코드만 작성. 기능 테스트가 완전해질 때까지 과정 2~3을 반복해야 할 수도 있다.
5. 기능 테스트를 재실행해서 통과하는 지 또는 제대로 동작하는지 확인. 이 과정에서 새로운 단위 테스트를 작성해야 할 수도 있다.

<br>
<br>

# 🍟 기능 테스트 실습
## 서버 실행 테스트_selenium
### 테스트 목표
1. 파이어폭스 브라우저 창을 실행하기 위해 selenium의 webdriver를 가동
2. 브라우저를 통해 로컬 PC상의 웹 페이지를 연다
3. 웹 페이지 타이틀에 "Django"라는 단어가 있는지 확인

### 첫 번째 코드
```python
from selenium import webdriver

browser = webdriver.FireFox()
browser.get('http://localhost:8000')

assert 'Django' in browser.title
```

이 테스트를 실행하기 위해서는 웹 브라우저인 `FireFox`가 설치 되어 있어야 한다. 
만약, `Chrome`으로 테스트 할 경우 `webdriver.Chrome()`으로 수정한다.

이 파일을 실행하면 `selenium`에러가 발생 하는데 페이지를 찾을 수 없다는 내용이다.
```python
selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//localhost%3A8000/&c=UTF-8&d=Firefox%EA%B0%80%20localhost%3A8000%20%EC%84%9C%EB%B2%84%EC%97%90%20%EC%97%B0%EA%B2%B0%ED%95%A0%20%EC%88%98%20%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4.
Stacktrace:
```
별도의 터미널 창에서 `Django` 서버를 실행 하면, 또 다른 에러가 발생한다.

```python
Traceback (most recent call last):
  File "functional_test.py", line 6, in <module>
    assert 'Django' in browser.title
AssertionError
```
`browser.title`가 `The install worked successfully! Congratulations!`으로 아래와 같이 문구를 변경한다.

```commandline
[...]
assert 'Congratulations!' in browser.title
```

테스트가 통과 되고 터미널에 아무런 에러 표시가 안 나오는 것을 볼 수 있다.


### 두 번째 코드 with `unittest`
`unittest` 모듈을 이용 해보자
```python
from selenium import webdriver
import unittest


class NewVisitorTest(unittest.TestCase):

    def setUp(self):
        self.browser = webdriver.Firefox()
        self.browser.implicitly_wait(3)

    def tearDown(self):
        self.browser.quit()
    
    def test_can_start_a_list_and_retrieve_it_later(self):
        # 에디스(Edith)는 멋진 작업 목록 온라인 앱이 나왔다는 소식을 듣고
        # 해당 웹 사이트를 확인하러 간다
        self.browser.get('http://localhost:8000')
        
        # 웹 페이지 타이틀과 헤더가 'To-Do'를 표시하고 있다
        self.assertIn('To-Do', self.browser.title)
        self.fail('Finish the test!')

if __name__ == '__main__':
    unittest.main(warnings='ignore')
```
- `unittest.TestCase`를 상속해서 테스트를 클래스 형태로 만든다.
- 테스트 메인 코드는 `test_can_start_a_list...`라는 메소드이다.
  - `test`라는 명칭으로 시작하는 모든 메소드는 테스트 메소드이며 테스트 실행자에 의해 실행된다.
  - 클래스 당 하나 이상의 테스트 메소드를 작성할 수 있다. 
  - 가능한 테스트 내용을 알 수 있는 테스트 메소드 명칭을 사용 하는 것이 좋다.
- `setUp`과 `teatDown`은 각 테스트 시작 전과 후에 실행 된다. 여기서는 브라우저를 시작하고 닫을 때 사용하고 있다.
  - 테스트에 에러가 발생해도 `tearDown`이 실행 된다. 
  - 단, `setUp`내에 `exceoption`이 있는 경우 `tearDown`이 실행 되지 않는다.
- 페이지 로딩이 끝날 때까지 기다렸다가 테스트하기 위해 `setUp`에 `implicitly_wait`를 추가한다.
  - `implicitly_wait`(암묵적 대기)는 필요에 따라 지정한 시간(초 단위)만큼 동작을 대기 상태로 둘 수 있다.
- `assertIn(a in b)`은 `a`가 `b` 안에 있으면 `True` 판별을 하는 메소드이다.


이제 다시 서버를 실행 시켜 테스트를 실행하면, 유용한 디버깅 정보와 도움이 되는 에러 메시지가 출력된다.
```python
======================================================================
FAIL: test_can_start_a_list_and_retrieve_it_later (__main__.NewVisitorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "functional_test.py", line 20, in test_can_start_a_list_and_retrieve_it_later
    self.assertIn('To-Do', self.browser.title)
AssertionError: 'To-Do' not found in 'The install worked successfully! Congratulations!'

----------------------------------------------------------------------
Ran 1 test in 3.336s
```

단위 테스트를 진행하면서 "To-Do" 타이틀 변경 에러를 해결해보자.

# 🥔 단위 테스트 실습
`startapp`을 통해 만들어진 `lists`앱에 `tests.py` 템플릿이 생성된다.

`Django`의 `TestCase`는 `unittest.TestCase`의 확장버전을 사용하고 있다.
단위 테스트의 경우에는 그것이 어떤한 형태든 자동화된 테스트 실행자에 의해 실행된다. 실패 테스트를 만들어 확인해보자.
```python
from django.test import TestCase

class SmokeTest(TestCase):
    
    def test_bad_maths(self):
        self.assertEqual(1 + 1, 3)
```

`functional_tests.py`는 우리가 직접 실행하지만 단위테스트는 테스트 실행자(`python manage.py test`)를 호출하여 실행 시킬 수 있다.
```python
❯ python manage.py test          
Found 1 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
F
======================================================================
FAIL: test_bad_maths (lists.tests.SmokeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/s2jiin/Develop/with/startlists/lists/tests.py", line 7, in test_bad_maths
    self.assertEqual(1+1, 3)
AssertionError: 2 != 3

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
Destroying test database for alias 'default'...

```

## 테스트 목표
### `Django`의 역할 및 처리 흐름
#### 역할
일반적인 웹 서버처럼 사용자가 특정 URL을 요청했을 때 어떤 처리를 할지 결정하는 것
#### 처리 흐름
1. 특정 URL에 대한 HTTP "요청"을 받는다.
2. `Django`는 특정 규칙을 이용해서 해당 요청에 어떤 뷰 함수를 실행할지 결정한다.(URL "해석"이라고 하는 처리)
3. 이 뷰 기능이 요청을 처리해서 HTTP "응답"으로 반환한다.

### 테스트 해야 할 것
1. URL의 사이트 루트('/')를 해석해서 특정 뷰 기능에 매칭시킬 수 있는가?
2. 이 뷰 기능이 특정 HTML을 반환하게 해서 기능 테스트를 통과할 수 있는가?

### 첫 번째 코드 : `test` 코드 작성
`lists/tests.py`에 아래 테스트 코드 작성
```python
# lists/tests.py
from django.urls import resolve
from django.test import TestCase


class HomePageTest(TestCase):

    def test_root_url_resolves_to_home_page_view(self):
        found = resolve('/')
        self.assertEqual(found.func, home_page)
```
- `resolve`는 `Django` 내부적으로 사용하는 함수, URL을 해석해서 일치하는 view 함수를 찾는다.
- 여기서는 "/"(사이트 루트)가 호출될 때 `resolve`를 실행해서 `home_page`라는 함수를 호출
- home_page 는 view 함수로 HTML을 반환한다. 

지금은 이 함수를 작성하지 않았기 때문에 아래 에러가 발생한다.

```python
ImportError: cannot import name 'home_page' from 'lists.views'
```

`ImportError`를 해결하기 위해 `views.py`에 `home_page`를 정의 해준다.

```python
# lists/views.py

from django.shortcuts impoert render

home_page = None
```

다시 테스트를 실행하면 아까와 다른 `Resolver404`라는 에러는 확인할 수 있다.
```python
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>]], 'path': ''}
```
"/"를 확인하려고 할 때 `Django404`에러를 발생시키고 있다. 즉, `Dajgno`가 "/"에 해당하는 URL 맵핑을 찾을 수 없다는 것이다.


### 두 번째 코드 : `urls.py`
`Django`는 urls.py를 이용해서 URL을 뷰 함수에 맵핑한다. 
```python
# superlists/urls.py

from django.contrib import admin
from django.urls import path, include
from lists.views import home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home'),
]
```
- `from lists.views import home_page`로 `import` 경로 설정하고 `path`를 추가하면 된다.

```python
TypeError: view must be a callable or a list/tuple in the case of include().
```
404가 에러 대신 `TypeError`가 발생한다.`home_page`가 호출할 수 있는 함수 형태가 아니여서 발생하는 에러이다. 

`views.py`에서 None을 실제 함수로 변경해보자. 모든 코드 변경은 테스트에 의해 검증되어야 한다.

```python
# lists/views.py

def home_page():
    pass
```

다시 테스트를 실행하면,

```python
❯ python manage.py test
Found 1 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
Destroying test database for alias 'default'...

```

휴, 드디어 첫 단위 테스트가 성공했다.


### 세 번째 코드 : `views.py`

단순히 빈 함수가 아닌 HTML 형식의 실제 응답을 반환하는 함수를 작성해야 한다.

tests.py 에 HTML형식 테스트를 추가한다.

```python
# lists/tests.py

from django.urls import resolve
from django.test import TestCase
from django.http import HttpRequest

from lists.views import home_page


class HomePageTest(TestCase):

    def test_root_url_resolves_to_home_page_view(self):
        found = resolve('/')
        self.assertEqual(found.func, home_page)

    def test_home_page_returns_correct_html(self):
        request = HttpRequest()
        response = home_page(request)
        self.assertTrue(response.content.startswith(b'<html>'))
        self.assertIn(b'<title>To-Do lists</title>', response.content)
        self.assertTrue(response.content.endswith(b'</html>'))
```
- `HttpRequest` 객체를 통해 사용자가 어떤 요청을 브라우저에 보내는지 확인한다.
- 이것을 `home_page`뷰에 전달해서 응답을 취득한다. 이 객체는 `HttpResponse`라는 클래스의 인스턴스다. 응답 내용이 특정 속성을 가지고 있는지 확인한다.
- 응답 내용이 <html></html>로 구성되어 있는지 확인한다. `response.content`는 `byte`형 데이터로, 파이썬 문자열이 아니다. 따라서 `b'` 구문을 사용해서 비교한다.
- `<title>` 태그에 "To-Do lists" 단어가 있는지 확인한다. 앞선 기능 테스트에서 확인한 것이기 때문에 단위 테스트도 확인해주어야 한다.

다시 단위 테스트를 실행하면 또 다른 에러가 나온다.
```python
======================================================================
ERROR: test_home_page_returns_correct_html (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/s2jiin/Develop/with/startlists/lists/tests.py", line 15, in test_home_page_returns_correct_html
    response = home_page(request)
TypeError: home_page() takes 0 positional arguments but 1 was given

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (errors=1)

```

### 단위 테스트 - 코드 주기
1. 터미널 단위 테스트를 실행해서 어떻게 실해파는지 확인한다.
2. 편집기상에서 현재 실패 테스트를 수정하기 위한 최소한의 코드를 변경한다.
3. 그리고 이것을 반복한다.

- 최소한의 코드 변경 : `request` 추가
  ```python
  # lists/views.py
  
  def home_page(request):
      pass
  ```
  
- 테스트
  ```python
  self.assertTrue(response.content.startswith(b'<html>'))
  AttributeError: 'NoneType' object has no attribute 'content'
  
  ----------------------------------------------------------------------
  Ran 2 tests in 0.001s
  
  FAILED (errors=1)
  ```
  
- 코드 : 가정한 대로 `Django.http.httpResponse`를 사용
  ```python
  # lists/views.py
  
  from django.http import HttpResponse
  
  
  def home_page(request):
      return HttpResponse()
  ```

- 다시 테스트
  ```python
  self.assertTrue(response.content.startswith(b'<html>'))
  AssertionError: False is not true
  
  ----------------------------------------------------------------------
  Ran 2 tests in 0.001s
  
  FAILED (failures=1)
  ```

- 다시 코드 : html 태그 추가
  ```python
  def home_page(request):
      return HttpResponse('<html><title>To-Do lists</title>')
  ```

- 테스트
  ```python
  self.assertTrue(response.content.endswith(b'</html>'))
  AssertionError: False is not true
  
  ----------------------------------------------------------------------
  Ran 2 tests in 0.001s
  
  FAILED (failures=1)
  
  ```

- 코드 : `</html>` 추가
  ```python
  def home_page(request):
      return HttpResponse('<html><title>To-Do lists</title></html>')
  ```

- 테스트 : 성공
  ```python
  Ran 2 tests in 0.001s
  
  OK
  Destroying test database for alias 'default'...
  
  ```

마지막으로 기능 테스트 실행하고 끝! 🎉
